packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  es5-ext: set this to true or false
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  unrs-resolver: set this to true or false
  youtube-dl-exec: set this to true or false
